[build]
  base = "frontend"
  command = "npm ci && npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "https://chatbot-saas-api.onrender.com/api/:splat"
  status = 200

[[redirects]]
  from = "/widget.js"
  to = "https://chatbot-saas-api.onrender.com/widget.js"
  status = 200

[[redirects]]
  from = "/health"
  to = "https://chatbot-saas-api.onrender.com/health"
  status = 200
